### PR TITLE
Roundtrip test

### PR DESCRIPTION
**Pull request by luciancancescu**
Add a roundtrip test.

### CODE REVIEW

**Comment by benoist** [comment]
Ah sorry buddy, I was just about to have a look at this PR 🤣

**Comment by luciancancescu** [comment]
Haha no worries, I’ll send in a moment another one 😂

How are you doing? What are you busy with?

**Comment by benoist** [comment]
I'm good! How are you?

I'm pretty busy with my own companies.
Currently working on these products (all related to each other)

https://cryptobasescanner.com
https://altrady.com
https://coinray.io

How about you?

**Comment by luciancancescu** [comment]
Wow, congrats for launching three products! The trading platform looks
great! Have you been to Zug already? It’s the capital of crypto currencies.

I’m good too. Busy working at Google Flights ✈️ and waiting for our first
baby🤰

**Pull request closed without merging**
